### ISSUE TITLE
Name of array is alredy a pointer (more the same bugs at once)

### ISSUE THREAD

**Issue by wilkwilq** [AnyLedger/anyledger-wallet#11]
https://github.com/AnyLedger/anyledger-wallet/blob/0ad6a780c63a7a7c31acb675234f7ae4f91d6b82/transaction.c#L34

https://github.com/AnyLedger/anyledger-wallet/blob/0ad6a780c63a7a7c31acb675234f7ae4f91d6b82/transaction.c#L39

https://github.com/AnyLedger/anyledger-wallet/blob/0ad6a780c63a7a7c31acb675234f7ae4f91d6b82/transaction.c#L44

https://github.com/AnyLedger/anyledger-wallet/blob/0ad6a780c63a7a7c31acb675234f7ae4f91d6b82/transaction.c#L50

https://github.com/AnyLedger/anyledger-wallet/blob/0ad6a780c63a7a7c31acb675234f7ae4f91d6b82/transaction.c#L56

https://github.com/AnyLedger/anyledger-wallet/blob/0ad6a780c63a7a7c31acb675234f7ae4f91d6b82/transaction.c#L62

https://github.com/AnyLedger/anyledger-wallet/blob/0ad6a780c63a7a7c31acb675234f7ae4f91d6b82/transaction.c#L69

https://github.com/AnyLedger/anyledger-wallet/blob/0ad6a780c63a7a7c31acb675234f7ae4f91d6b82/transaction.c#L75

https://github.com/AnyLedger/anyledger-wallet/blob/0ad6a780c63a7a7c31acb675234f7ae4f91d6b82/transaction.c#L81

https://github.com/AnyLedger/anyledger-wallet/blob/0ad6a780c63a7a7c31acb675234f7ae4f91d6b82/transaction.c#L100

https://github.com/AnyLedger/anyledger-wallet/blob/0ad6a780c63a7a7c31acb675234f7ae4f91d6b82/transaction.c#L110

https://github.com/AnyLedger/anyledger-wallet/blob/0ad6a780c63a7a7c31acb675234f7ae4f91d6b82/transaction.c#L128
Getting address here with & is not necessary

**Comment by pcppcp** [comment]
closing this as it's been fixed. Next time please an aggregate issue for such small updates.
