### ISSUE TITLE
Test cases for web3 implementations are failing.

### ISSUE THREAD

**Issue by MohitKumarAgniotri** [AnyLedger/anyledger-wallet#121]
In the below file, 
https://github.com/AnyLedger/anyledger-wallet/blob/master/tests/CMakeLists.txt
line 97 must be modified to run correct test cases for web3.  At the moment, when the tests are enabled, they fail.

**Comment by lorepieri8** [comment]
@MohitKumarAgniotri Can you put a more descriptive name for the issue?
