### ISSUE TITLE
Evaluate available COAP libraries

### ISSUE THREAD

**Issue by pcppcp** [AnyLedger/anyledger-wallet#13]
Ideal candidate should be:

- no (minimal) 3rd party dependencies
- actively maintained
- compileable for both x86 and embedded targets
- support full RESTful client capabilities
- open source ;)

there's a nice list of implementations on Wikipedia
https://en.wikipedia.org/wiki/Constrained_Application_Protocol

**Comment by lorepieri8** [comment]
@danielinux @MohitKumarAgniotri  Any suggestions?

Leshan is using Californium, while wakaama (another LWM2M implementation, but in C) uses a modified version of Erbium's CoAP.

https://www.eclipse.org/leshan/
https://github.com/eclipse/wakaama/

**Comment by lorepieri8** [comment]
Also, does not Zephyr RTOS already have a coap implementation?

https://github.com/zephyrproject-rtos/zephyr/blob/master/include/net/coap.h
