### ISSUE TITLE
warning-free zephyr builds

### ISSUE THREAD

**Issue by pcppcp** [AnyLedger/anyledger-wallet#135]
- [ ] use #pragma to silence warnings that come from zephyr includes
- [ ] enable `-Werror` for zephyr builds

**Comment by vishav26** [comment]
Hi,

I saw this on cmake documentation. Add -Werror=dev while building zephyr. 
https://cmake.org/cmake/help/v3.12/manual/cmake.1.html

**Comment by pcppcp** [comment]
that's completely unrelated; that flags is meant to raise errors when parsing `cmakelists.txt` files

**Comment by pcppcp** [comment]
Fixed by #144
