### ISSUE TITLE
cmake error in the x86 build

### ISSUE THREAD

**Issue by bnyf** [AnyLedger/anyledger-wallet#157]
In the x86 build, when I excute the command `cmake -GNinja ../`, I get the error as blow.

    CMake Warning (dev) in CMakeLists.txt:
    No cmake_minimum_required command is present.  A line of code such as

        cmake_minimum_required(VERSION 3.10)

    should be added at the top of the file.  The version specified may be lower
    if you wish to support older CMake versions for this project.  For more
    information run "cmake --help-policy CMP0000".
    This warning is for project developers.  Use -Wno-dev to suppress it.

    -- Configuring done
    CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
    Missing variable is:
    CMAKE_C_COMPILE_OBJECT
    CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
    Missing variable is:
    CMAKE_C_ARCHIVE_CREATE
    CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
    Missing variable is:
    CMAKE_C_ARCHIVE_FINISH
    CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
    Missing variable is:
    CMAKE_C_COMPILE_OBJECT
    CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
    Missing variable is:
    CMAKE_C_ARCHIVE_CREATE
    CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
    Missing variable is:
    CMAKE_C_ARCHIVE_FINISH

The all dependences I installed successfully.
I tried some solutions searched on google but they didn't work.

 - OS: Ubuntu
 - Version 18.04.1 LTS

**Comment by lorepieri8** [comment]
Partially addressed in b4a60b94ac2147588292ce2a2c8b7e2562f329b0.
