### ISSUE TITLE
eth module: `address_from_signature()`

### ISSUE THREAD

**Issue by pcppcp** [AnyLedger/anyledger-wallet#29]
Create function
`int address_from_signature(const uint8_t *data, size_t data_len, const signature_t *signature, address_t *addr_out)`

Params:

- `const uint8_t *data` - data
- `size_t *data_len` - size of the data buffer
- `const signature_t *signature` - signature of the data
- `address_t *addr_out` - recovered address

see:
https://web3js.readthedocs.io/en/1.0/web3-eth-personal.html#ecrecover

Return value:
- 0 - success
- -1 - error

**Comment by MohitKumarAgniotri** [comment]
I will start working on this issue. Also, serves as a good learning point for me.

**Comment by MohitKumarAgniotri** [comment]
If I understand correctly, this is how it must be done
- Use the data and generate the signed data for the same using the stored private key(s)
- Match the resulting signed data with the sign passed in the API
- Verify the signature match
  -- if they do: Return the address associated with the key
  -- If they don't: Repeat the steps with the next pair

@pcppcp @randomshinichi Do share your views.

**Comment by pcppcp** [comment]
No. Please read documentation of [ecrecover](https://web3js.readthedocs.io/en/1.0/web3-eth-personal.html#ecrecover) mentioned in the issue description.

The function takes data + signature and recovers public key from the signature. No signing is required.
