### ISSUE TITLE
CI: prepare a gcc docker image for circleCI

### ISSUE THREAD

**Issue by pcppcp** [AnyLedger/anyledger-wallet#30]
Problem:
We are using CircleCI for the pull requests CI. However, CircleCI doesn't provide an image with all the required tools installed.
For now the setup uses CircleCI's python3.6 image, plus a script that installs C related dependencies.
What's wrong? Python image is too big (it includes browsers and node.js and whatnot), and dependencies must be installed for every run.

- [ ] create a docker setup using basic CircleCI's ubuntu image
- [ ] install [dependencies](https://github.com/AnyLedger/anyledger-wallet/blob/master/.circleci/install_deps.sh) to it
- [ ] make sure the image can be used by the CircleCI runs (PR's CI has to pass anyway)
- [ ] there should be a method to repeatedly rebuild the image (in case we want to update the base system or install additional tools)

resources:
https://circleci.com/docs/2.0/custom-images/

**Comment by GPRESean** [comment]
I know how to write down Dockerfile. I will create a merge request after I test if it can build this project without problem.
