### ISSUE TITLE
[META] Getting data out of the board

### ISSUE THREAD

**Issue by pcppcp** [AnyLedger/anyledger-wallet#53]
A very important part is a working network connection from the board to the outside world.

#### LoWPAN6 BLE connection
Our primary target

Pros:
- cool and wireless
- full network stack
- can use any linux PC as a gateway

Cons:
- hard to set up

#### PPP
network transport utilizing serial port. Not sure if it is possible to have more USB serial connections in Zephyr

Pros:
- full network stack
- compatible with most OS

Cons:
- not sure if there's a support for this network layer in Zephyr
- requires a USB connection

#### Mock script
For a quick demo we can set up a script reading data from the ttyACM serial line and sending them to our gateway/ethereum node/Leshan

Pros:
- easy to set up

Cons:
- no 2-way connection
- app specific

**Comment by pcppcp** [comment]
this example for 6lowpan connection from Zephyr works quite well, will investigate further

https://docs.zephyrproject.org/1.13.0/samples/bluetooth/ipsp/README.html

**Comment by pcppcp** [comment]
We will use 6lowpan (nrf52x) and SLIP (qemu) as the networking stack.

**Comment by devtodev** [comment]
Hi! I know, this issue is closed, but I want to let you know my vision about it. Maybe could be a wise idea keeping decoupling between the Anyledger-Wallet C Library and the board or any OS, in this case Zephyr and have a new project to do this kind of demos.

**Comment by randomshinichi** [comment]
Of course, we have no plans to be beholden to Zephyr or the board!
