### ISSUE TITLE
Could NOT find Threads (missing: Threads_FOUND)

### ISSUE THREAD

**Issue by vishav26** [AnyLedger/anyledger-wallet#56]
Hi,
I am new here and I am trying to setup the environment for the build. I am getting this error:
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  **Could NOT find Threads (missing: Threads_FOUND)**
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindThreads.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  tests/CMakeLists.txt:3 (find_package)

I have successfully installed pthreads using this command:
**sudo apt-get install libpthread-stubs0-dev**

But still I am getting this error. Can someone help me here please?

Regards
Vishav

**Comment by lorepieri8** [comment]
Not sure if this is relevant: https://stackoverflow.com/questions/15193785/how-to-get-cmake-to-recognize-pthread-on-ubuntu

**Comment by vishav26** [comment]
Hi @lorepieri8 
Thanks but I guess this is not the issue. I see following in CMakeLists.txt
**set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=gnu11 -pedantic -Wall -Wextra")
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++14 -pedantic -Wall -Wextra")**

It does lists C.
Regards
Vishav

**Comment by pcppcp** [comment]
Hey @vishav26, have you figured this one out?

**Comment by vishav26** [comment]
Hi,

Sorry. This was my bad. I forgot to install the requirements. I again cloned the project and build again today. Successfully built x86 builds. Now working on Zephyr builds.

Thanks & Regards 
Vishav
