### ISSUE TITLE
Is crypto folder necessary?

### ISSUE THREAD

**Issue by GPRESean** [AnyLedger/anyledger-wallet#96]
Are crypto folder and its contents remained for later use?

I guess that this crypto is legacy code. I was able to build the project without that code. With this [Commit Diff](https://github.com/GPRESean/anyledger-wallet/commit/ad7cbd3c504485e791683a64c6e4d910d1c8cc5f)

If my guess is correct and it is safe to remove crypto, I will make a pull requests to remove it.

Appearances:
[cmake/wallet.cmake:8](https://github.com/AnyLedger/anyledger-wallet/tree/a0a9b98dc3068b20467a98d3f135bd38e03736fb/cmake/wallet.cmake#L8)
[cmake/wallet.cmake:14](https://github.com/AnyLedger/anyledger-wallet/tree/a0a9b98dc3068b20467a98d3f135bd38e03736fb/cmake/wallet.cmake#L14)
[eth/transaction.c:10](https://github.com/AnyLedger/anyledger-wallet/tree/a0a9b98dc3068b20467a98d3f135bd38e03736fb/eth/transaction.c#L10)
[eth/transaction.c:94](https://github.com/AnyLedger/anyledger-wallet/tree/a0a9b98dc3068b20467a98d3f135bd38e03736fb/eth/transaction.c#L94)
[helpers/crypto_helper.c](https://github.com/AnyLedger/anyledger-wallet/tree/a0a9b98dc3068b20467a98d3f135bd38e03736fb/helpers/crypto_helper.c)
[helpers/crypto_helper.h](https://github.com/AnyLedger/anyledger-wallet/tree/a0a9b98dc3068b20467a98d3f135bd38e03736fb/helpers/crypto_helper.h)

**Comment by pcppcp** [comment]
You are correct; these functions are obsolete after the `trezor-crypto` has been introduced.

It's probably safe to remove them - we can always pull them from history if needed.
